# Generated by Django 3.2.23 on 2024-02-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userd_user_emergency_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='userd',
            name='user_race',
            field=models.CharField(choices=[('/', 'American Indian'), ('/', 'Asian'), ('/', 'African American'), ('/', 'Native Hawaiian'), ('/', 'White')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
